timezone: America/Phoenix
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "pages"
  -
    scope:
      path: "index.html"
      type: "page"
    values:
      layout: "index"
visible-categories: [dota]
baseurl: /techniques
