timezone: America/Phoenix
defaults:
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "pages"
visible-categories: [dota, javascript, css, programming]
kramdown:
  input: GFM
gems:
- jekyll-mentions
